apiVersion:  apps/v1
kind: Deployment
metadata:
  name: deploy-react-kubernetes-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: sofia
        image: oussema1994/sofia:{{BUILD_NUMBER}}
        ports:
        - containerPort: 3000
