kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: oussema1994/sofia:{{BUILD_NUMBER}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always
