apiVersion: v1
kind: Service
metadata:
  name: deploy-react-kubernetes-service
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
