apiVersion: v1
kind: Service
metadata:
name: scores-service-lb
labels:
   app: scores-service-lb
spec:
   type: LoadBalancer
   ports:
   - port: 80
     targetPort: 3000
     name: score-http
   selector:
     app: scores-service
